name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release-npm:
    name: Release NPM (${{ github.ref }})
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if Tag on Main
        run: |
          git checkout main
          branch=$(git branch main --contains ${{ github.ref }})
          git checkout ${{ github.ref }}
          if [ -z $branch ]; then
              echo "Tag ${{ github.ref }} is not contained in the main branch."
              exit 1
          fi

      - name: Setup PNPM
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
          run_install: false

      - name: Build & Test
        run: pnpm i && pnpm build && pnpm test

      - name: Publish
        run: |
          pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          pnpm publish --verbose --no-git-checks

  release-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Regctl
        run: npm i -g regctl

      - name: Build & Push
        run: |
          docker buildx bake --push --set "*.platform=linux/arm64,linux/amd64"
          regctl -v info image copy jacoblincool/pure-cat:latest ghcr.io/jacoblincool/pure-cat:latest

  release-note:
    name: Release Note (${{ github.ref }})
    runs-on: ubuntu-latest
    needs:
      - release-npm
      - release-image
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check if Tag on Main
        run: |
          git checkout main
          branch=$(git branch main --contains ${{ github.ref }})
          git checkout ${{ github.ref }}
          if [ -z $branch ]; then
              echo "Tag ${{ github.ref }} is not contained in the main branch."
              exit 1
          fi

      - name: Publish Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GH_TOKEN }}"
          prerelease: false
          files: |
            README.md
            LICENSE
